DROP TABLE 'users';

CREATE TABLE 'users' (
  'id' mediumint(8) unsigned NOT NULL auto_increment,
  'firstname' varchar(255) default NULL,
  'surname' varchar(255) default NULL,
  'email' varchar(255) default NULL,
  'address' varchar(255) default NULL,
  'city' varchar(255),
  'postcode' varchar(10) default NULL,
  'lat' varchar(30) default NULL,
  'lng' varchar(30) default NULL,
  'company' varchar(255),
  PRIMARY KEY ('id')
) AUTO_INCREMENT=1;

INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Phillip","Webster","ac@luctusfelis.com","Ap #142-8332 Tellus Rd.","Colmar","K19 7VQ","-18.29782","-40.43469","Dolor Company");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Arden","Dixon","Ut@maurisut.org","9349 Et Rd.","Hull","JQ9 7ND","4.41149","-139.71931","Consectetuer LLP");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Aspen","Woodward","dolor@vulputateposuerevulputate.net","Ap #800-3221 Libero Road","Solesino","DR47 9VQ","-68.82277","-105.9883","Convallis Corporation");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("John","Baird","Nam.consequat.dolor@natoquepenatibus.net","177 Integer Street","Virginia Beach","KE5W 8SK","59.98643","-126.10669","Cras Vehicula Aliquet Foundation");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Veda","Baird","velit@urna.com","344-9291 Tempus, Ave","St. Thomas","NN07 3PD","69.49365","156.8097","Pharetra Felis Associates");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Calvin","Lee","dui.in.sodales@Loremipsum.com","P.O. Box 487, 9298 Mollis Street","Beez","AF7Q 7UP","-40.07737","105.12771","Quisque Consulting");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Blythe","Rogers","non@Duis.com","P.O. Box 122, 1262 Vitae, St.","Sombreffe","H9 3PR","4.48033","74.19494","Ac Mi Eleifend Institute");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Zelenia","Combs","nostra@eudoloregestas.com","Ap #385-1569 Sit Av.","Hï¿½rouxville","H6 3AM","0.65017","-129.5608","Praesent Associates");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Illana","Cardenas","malesuada.vel.convallis@Duisgravida.co.uk","438-1275 Hymenaeos. Avenue","Gavirate","AK7 8PI","-2.41354","-87.73429","Laoreet Incorporated");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Conan","Rollins","convallis@vulputaterisus.edu","100-9162 Maecenas Ave","Mignanego","VE10 3VO","53.66969","94.51359","Lectus Cum Incorporated");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Tamekah","Townsend","hendrerit@bibendumullamcorperDuis.ca","783-9570 Tempus Street","Wagnelï¿½e","J6Z 9YM","-14.25534","165.29423","Magna Nec Quam LLC");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Price","Burch","ac.mattis@diam.net","9505 Elit Road","Grandrieu","UL0 6UB","30.80648","113.9577","Rutrum Justo Praesent Foundation");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Hayden","Coffey","laoreet@ac.com","2606 Ac Ave","Sint-Katherina-Lombeek","V65 0PB","-7.1803","-141.52758","Vestibulum Massa Rutrum Institute");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Gannon","Acosta","vel.est@vulputate.edu","5225 Urna Rd.","GroÃpetersdorf","DU24 2CH","45.1828","156.21074","Mauris Ut Quam PC");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Gil","Morrison","Mauris@Integeraliquamadipiscing.co.uk","8287 Malesuada Avenue","Villa Cortese","QY3 9WN","-63.0117","22.15322","Dictum Placerat Inc.");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Quyn","Schultz","metus.Aliquam@arcu.edu","720-5996 Ullamcorper, St.","Saint-Hilarion","K80 6FS","-5.4403","-37.14048","Taciti Company");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Julian","Britt","ut.quam@aliquamenimnec.com","354-1552 Amet, Av.","Dolembreux","P5C 6EJ","10.25619","-1.2082","Nulla Company");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Constance","Daniel","et@consectetuer.com","Ap #820-9884 Vivamus Road","Swansea","I1 1QM","-76.81279","29.74914","Vitae Industries");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Sandra","Terry","odio@at.co.uk","2236 Nulla. St.","LogroÃ±o","R2L 5HZ","32.53412","-116.26737","Commodo Auctor Corporation");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Ahmed","Cash","ut.erat@eu.ca","4387 Faucibus Road","Morpeth","Q8 8KF","-1.41616","-130.02017","Arcu Inc.");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Reuben","Dennis","Donec.feugiat.metus@elitsedconsequat.com","495-5123 Tristique St.","Fairbanks","U9 7WY","49.40505","147.31257","Malesuada Limited");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Abdul","Delacruz","Quisque.purus@malesuadaut.co.uk","Ap #419-5173 Egestas. Road","Fairbanks","A0V 1ED","83.02013","81.48402","Mauris Limited");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Josephine","Shepard","vel@Fuscefermentum.co.uk","P.O. Box 340, 9633 Et Rd.","St. Paul","P9 8YP","-9.88126","-76.57855","Non PC");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Dillon","Dennis","Cras@arcuMorbi.net","Ap #732-3577 Arcu. Rd.","San Antonio","CO34 3NG","40.99299","-102.22425","Ante LLP");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Illiana","Bolton","Sed@sociisnatoquepenatibus.ca","Ap #738-8498 Primis Avenue","Sint-Agatha-Berchem","QQ6 0CX","69.25613","-27.37056","Adipiscing Mauris Corp.");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Jaquelyn","Perez","et.netus@antedictum.net","7083 Dui, Av.","Nakusp","UP4E 3OR","-29.3471","58.08438","Fermentum Metus Aenean Ltd");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Vance","Young","Nullam.suscipit@primisinfaucibus.com","990-4569 Lacinia Rd.","Newtown","QL47 9TH","-37.02878","-161.86266","Sem Semper Industries");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("William","Meyers","ut@Quisqueornare.org","788-3670 Adipiscing Street","Tsiigehtchic","MW6Z 9DA","-33.69916","-85.08911","Non Lacinia Company");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Demetria","Delaney","et.arcu.imperdiet@Sedeget.org","3414 Nec, Rd.","Renfrew","UQ2I 5FS","-24.44784","-158.58578","Nisl Maecenas LLC");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Scarlett","Morton","viverra.Maecenas@non.org","585-8404 Cras Ave","Dolembreux","MO1M 2EJ","17.27671","156.26289","Convallis Dolor Quisque Corp.");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Iris","Stevens","et@sempereratin.org","P.O. Box 978, 5830 Vitae Ave","Cicagna","IG60 1HB","-59.88357","-72.16544","Vulputate Risus Ltd");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Ora","Reid","dolor.sit.amet@semperduilectus.co.uk","592 Nulla. St.","Lacombe","T3 7AR","5.56269","-117.94658","Dictum Cursus Associates");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("James","Maldonado","interdum@idrisusquis.edu","336-286 Dictum Street","De Klinge","RD5Q 2FH","-48.01736","99.93461","Aliquet Foundation");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Irma","Waller","nascetur@tellus.ca","747-5179 Ante, Ave","Fort Saskatchewan","UB09 4NB","-62.58719","65.80047","Tempor Augue Ac Ltd");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Joel","Oneill","semper.auctor@orciUtsagittis.org","Ap #854-1526 Libero. Av.","Villers-lez-Heest","NV4 0AK","-38.7668","-54.60416","Fringilla PC");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Steel","Fuentes","erat.vel@sed.com","P.O. Box 798, 9573 Ac St.","Ruvo del Monte","L9 7TI","35.24693","124.38468","Curabitur Consequat Lectus Incorporated");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Amery","Puckett","urna@tristiquenequevenenatis.com","P.O. Box 918, 5915 Posuere Rd.","Telfs","U90 0OF","-20.38201","-50.01752","Est Nunc Laoreet Foundation");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Aristotle","Mcdonald","porta@Donec.com","P.O. Box 587, 9292 Nec, Rd.","Thunder Bay","M1 6NN","-50.33348","-104.74864","Nulla Interdum Inc.");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Beverly","Hardin","ante.Vivamus@ac.com","Ap #407-582 Vel Avenue","Paglieta","ZL0C 1ND","4.55315","171.7842","Interdum Sed Auctor Inc.");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Kellie","Rocha","nec.urna@placeratorci.ca","P.O. Box 502, 9944 Et St.","Dallas","IS18 5MQ","-59.21778","-178.15839","Pellentesque Ultricies Inc.");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Barrett","Hopkins","nulla.magna@nisidictumaugue.edu","713-9054 Blandit Avenue","Yorkton","L9S 9WB","-2.4804","-139.5186","Urna Company");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Octavius","Avila","ut@primisinfaucibus.co.uk","Ap #858-3034 Amet Av.","Haverhill","CW40 9JW","30.22957","-56.54027","Eleifend Nunc Inc.");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Quinn","Logan","orci@nibhdolornonummy.co.uk","P.O. Box 443, 1067 Nisi. Rd.","Miami","Q5 6DT","-67.84441","123.91206","Ipsum LLC");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Mariam","Pratt","sagittis@lacuspede.co.uk","1763 Justo Ave","Bozeman","W1 7UW","-3.06296","19.53802","Donec Egestas Duis LLC");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Nissim","Potts","Donec.egestas.Aliquam@VivamusnisiMauris.net","549-1557 Cras St.","Gravelbourg","J33 0NG","34.94257","111.26686","Ut Nec Foundation");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Wyatt","Wilkinson","Phasellus.dapibus@lobortisauguescelerisque.ca","Ap #337-4409 Quam, Rd.","Sh?diac","BW0S 8NE","-1.00526","-168.57424","Suspendisse Sed Company");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Kasper","Hebert","augue.porttitor.interdum@afelis.net","Ap #803-4626 Non Rd.","Evesham","X4 3GH","-42.82834","-61.33122","Ipsum Primis Associates");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Owen","Sparks","ac.facilisis.facilisis@faucibusutnulla.net","P.O. Box 933, 2233 Risus. Rd.","St. Neots","J9 4VU","59.08773","10.39826","Curabitur Ut Odio Consulting");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Tiger","Flores","sollicitudin.adipiscing@iaculis.com","P.O. Box 706, 6286 Imperdiet Street","Caplan","E4 2TX","84.15481","-98.84464","Orci Tincidunt Adipiscing Corp.");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Zia","Sims","Proin.ultrices@ut.org","5863 Feugiat Rd.","CÃ¡ceres","A5J 0WX","27.62506","-138.87301","Ut Sem Nulla Consulting");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Nathaniel","Hebert","neque@pedeCumsociis.net","147-1998 Scelerisque St.","Eisden","PY0N 9VV","20.42944","-88.16925","Ut Foundation");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Claire","Jordan","nibh.Aliquam@loremlorem.net","396-4600 Etiam St.","Maastricht","D43 5YV","-48.21562","-99.8406","Lectus Cum Company");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Hope","Wise","ornare.facilisis.eget@risusaultricies.com","8372 Amet Road","Villers-aux-Tours","SJ7 4YW","-83.27021","87.66217","Tempus Non Limited");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Courtney","Schultz","Suspendisse.ac@et.edu","Ap #458-2371 Nascetur Avenue","Basildon","CQ00 3BK","-29.75092","-137.06732","Nascetur Ridiculus Mus Inc.");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Vernon","Lowery","risus.a.ultricies@amet.ca","P.O. Box 984, 3208 Ut Rd.","Metairie","BB4Q 2SV","33.87872","85.10529","Vitae Aliquet Inc.");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Driscoll","Mejia","fermentum@egetvenenatis.co.uk","Ap #994-1469 Eleifend. Rd.","Preston","TI3 1YF","-19.10786","86.52851","Congue Corp.");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Nora","Calhoun","Vestibulum.accumsan@sitametdiam.com","296-3320 Dui Av.","Fort Worth","UB54 8EM","25.40182","8.10482","Leo In PC");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Carissa","Gay","amet.ante.Vivamus@liberoProin.org","5608 Tellus Av.","Posina","JR0 9MX","-42.40956","11.79649","Facilisis Eget Associates");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Holmes","Herman","felis.ullamcorper@senectuset.co.uk","5939 Donec Av.","Seilles","R37 3HO","-24.74854","169.42271","Non Justo Institute");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Xavier","Ortiz","nulla.ante@felisNullatempor.co.uk","P.O. Box 175, 6722 Donec Rd.","San Costantino Calabro","AP7U 7AV","4.49681","74.02002","Velit Eget Industries");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Howard","Salas","aliquet.Phasellus@purusgravidasagittis.edu","180-3934 Nec Av.","Ramskapelle","Q5 0OB","-70.5094","96.66639","Pellentesque Consulting");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Melodie","Hobbs","pede@pede.com","P.O. Box 570, 9652 Ante, Ave","Scandriglia","XB3 8SS","33.77291","161.27227","Neque Morbi Industries");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Ila","Sellers","ac@nislarcuiaculis.com","P.O. Box 624, 8414 Nec Avenue","Conca Casale","R5 4KI","18.45558","-131.61268","Pede Blandit Congue LLC");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Lana","Orr","nec.urna.et@duiin.com","408-5761 Eleifend Rd.","Cobourg","JU2 1AE","-40.33335","-137.90372","Mauris Magna Company");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Samantha","Mullen","enim.diam@imperdietornare.net","P.O. Box 200, 1548 Aenean Rd.","Priolo Gargallo","WV6 2SI","46.12353","-155.18379","Mauris Associates");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Vaughan","Henry","at@natoque.co.uk","7783 Erat Avenue","Dunbar","W2F 6EM","-3.87754","83.45179","Egestas Hendrerit PC");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Elijah","Klein","dui.Fusce.diam@tortorNunccommodo.org","884-4986 Sed Rd.","Abbotsford","JN5 7EI","-81.68608","169.62687","Posuere At Ltd");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Skyler","Francis","euismod.urna@Duis.ca","Ap #104-7438 Nisl. Street","Varsenare","E1R 8SU","-13.78824","113.30703","Arcu Consulting");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Jelani","Norman","tincidunt.adipiscing.Mauris@egestas.co.uk","439-5426 Donec Road","Canterano","W65 6WE","-49.48904","89.0521","Praesent Luctus Incorporated");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Adrian","Jensen","lorem.eu@Sedneque.org","2578 Eleifend Rd.","Antey-Saint-AndrÃ¨","F55 2GO","-79.6982","112.81867","Et Commodo Institute");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Amos","Barry","vitae.purus@quama.org","P.O. Box 779, 4620 Elit Ave","Vierzon","YO1 1MU","62.27052","40.1127","Non Enim Commodo Associates");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Paloma","Burgess","Quisque.purus.sapien@sapien.net","6278 Volutpat. Road","Grand-Rosiï¿½re-Hottomont","B8Y 8TQ","88.74931","-113.08458","Lorem Institute");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Daquan","Schultz","metus.urna@acfacilisisfacilisis.com","1079 Phasellus St.","Whyalla","J64 5YL","14.83395","164.99172","Lectus Inc.");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Kirestin","Schroeder","lobortis.augue@nuncnullavulputate.co.uk","Ap #341-1264 Quisque Street","Glovertown","M7 7PK","-11.47587","156.39699","Nunc Pulvinar Arcu Consulting");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Shad","Meyers","euismod@convallisligulaDonec.org","P.O. Box 913, 5383 Lorem Avenue","ChapecÃ³","UJ0 7UB","65.91845","20.81723","Lacus Limited");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Hope","Ashley","mauris.Integer.sem@sem.co.uk","408-8542 Vel, Road","Beerse","Z9 5UP","-67.18385","31.38163","Et Pede Nunc Foundation");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Kylan","Merrill","risus.at.fringilla@cubiliaCuraeDonec.edu","P.O. Box 322, 8448 Rutrum Street","Tsiigehtchic","T64 1MN","-52.61418","-82.94408","Nulla Interdum Ltd");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Carla","Merrill","justo@mattisornarelectus.org","P.O. Box 739, 8937 Amet Av.","St. Petersburg","X3H 0QD","85.22292","54.92","Imperdiet Erat Associates");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Dorothy","Harris","neque@euligulaAenean.co.uk","Ap #336-2779 Est, Av.","Gander","N2 5XE","-26.10439","149.41382","Sed Nulla Ante Foundation");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Kamal","David","id.erat.Etiam@ut.net","6525 Scelerisque Road","Millet","EX7Y 4WM","-66.51031","23.56766","Quis Industries");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Mallory","Mcknight","risus@dictumeuplacerat.co.uk","P.O. Box 702, 1451 Auctor, Ave","Falkirk","WL30 7JW","-83.76869","48.29705","Vel Arcu Curabitur Limited");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Maya","Bell","dui@mi.ca","249-590 Non Avenue","Beho","HB37 2OP","-71.55484","72.0262","Sed Molestie LLC");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Wang","Cruz","Aenean@vulputateeuodio.net","Ap #350-6966 Egestas. St.","Kent","C36 4GA","-80.8972","-135.5009","Odio A Purus Inc.");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Quemby","Davidson","risus.Morbi.metus@necmollisvitae.com","Ap #227-9877 Dui Rd.","Baisy-Thy","A6I 8RO","55.10011","-104.52458","Integer Mollis Company");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Giselle","Martinez","Donec.tempus@Sedegetlacus.co.uk","Ap #165-4373 Elit, Ave","Gentinnes","TY5 2CP","46.21368","-117.13416","Lobortis Class Industries");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Keegan","Knowles","augue@Fuscedolorquam.org","P.O. Box 266, 7091 Aliquet, St.","Kingston","NB8T 7XF","-62.47976","-166.35193","Dui Inc.");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Halee","Lara","Etiam.gravida@Vivamus.co.uk","P.O. Box 869, 9129 Netus Rd.","Montemesola","V8J 7SW","53.90626","172.1442","Erat Incorporated");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Leonard","Parker","rhoncus.Donec.est@sedest.com","8158 Quisque St.","l'Ecluse","OS4V 7ZR","-63.83306","88.2605","Urna Convallis Erat LLC");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Harrison","Bean","posuere@sitamet.com","Ap #907-6078 Morbi Street","Sibret","G06 4ZD","36.76309","-136.13254","Suspendisse Eleifend Foundation");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Kadeem","Kramer","hendrerit.neque.In@felisadipiscingfringilla.edu","Ap #317-4918 Non Ave","Langenburg","W4S 5FE","18.51647","-14.698","Et Libero Corporation");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Carly","Levy","nunc@auctorMauris.edu","2595 In, St.","Wangaratta","ZS7K 8NQ","6.31147","20.3297","Vestibulum Consulting");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Josephine","Bennett","morbi.tristique.senectus@molestieorcitincidunt.co.uk","351-5178 Donec Rd.","Haasdonk","V7 4CJ","75.06296","-176.36777","Euismod Corporation");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Bertha","Rosario","quam@ullamcorperviverraMaecenas.com","314-753 In Av.","Diepenbeek","I1V 4SF","21.50695","-64.79988","Erat Vivamus Nisi Associates");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Jin","Dotson","augue.eu@ultricesDuisvolutpat.ca","Ap #723-7371 Ac Av.","Champion","O5B 7OX","-34.57401","53.65256","Arcu Aliquam Incorporated");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Sonia","Rhodes","iaculis.aliquet.diam@nibhenimgravida.ca","6109 Molestie Ave","Governador Valadares","YR20 0CM","-55.56827","21.18085","Cras Interdum Nunc Foundation");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Brennan","Byrd","ut.sem.Nulla@ipsumSuspendissesagittis.edu","Ap #350-2926 Non, Street","Neath","IA72 8YX","78.15495","65.72116","Ligula Consectetuer Limited");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Violet","Bradshaw","nec@quis.com","P.O. Box 205, 8450 Non, Av.","Solihull","KR6 1XJ","50.82963","113.11036","Sapien Molestie Corporation");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Tashya","Fisher","velit.egestas@malesuadafames.co.uk","P.O. Box 238, 192 Nulla. Road","Caprino Bergamasco","W1V 8VF","64.36164","-124.7306","Enim Corp.");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Marvin","Sexton","aliquet.molestie.tellus@vitaeeratvel.com","P.O. Box 981, 2944 Ultricies Av.","GroÃpetersdorf","T1 5YU","76.75812","-151.5313","Non Industries");
INSERT INTO 'users' ('firstname','surname','email','address','city','postcode','lat','lng','company') VALUES ("Maggie","Collier","laoreet@nibhDonec.net","Ap #165-3609 Rutrum St.","Villa Agnedo","X7V 8GY","-1.75327","-134.2925","Sed Eget Inc.");
